# Generated by Django 3.0.8 on 2020-09-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200919_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
